### ISSUE TITLE
Disabling status indicator throws an error

### ISSUE THREAD

**Issue by VinDotRun** [ElectricityMachine/SCR-SGPlus#79]
If you set `enable_status_indicator` to `false` and press the keybind to toggle the macro, the following exception is thrown:
```python
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "keyboard\_generic.py", line 58, in process
  File "keyboard\__init__.py", line 218, in pre_process_event
  File "keyboard\__init__.py", line 649, in <lambda>
  File "script.py", line 671, in <lambda>
  File "script.py", line 285, in toggle_disable
  File "script.py", line 74, in update_label
NameError: name 'label' is not defined
```
This causes the script to stop working entirely.

**Comment by ElectricityMachine** [comment]
Thanks for reporting this. I had fixed this in my local version, but didn't push those changes before releasing.

Will be fixed in the next version, either by me or another contributor.
